### ISSUE TITLE
Not loading today

### ISSUE THREAD

**Issue by milan-j** [ryanbrainard/forceworkbench#708] opened 2017-08-11 12:49 UTC
After I go to https://workbench.developerforce.com/ I get this message:

Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by AlphaCharlieBravo** [comment] 2017-08-11 12:54
Same here, it's been down for a couple of hours now.

**Comment by milan-j** [comment] 2017-08-11 12:56
It's OK now.

**Comment by cgorshing** [comment] 2017-08-17 14:40
Duplicate of #710

**Closed** 2017-10-04 22:56 UTC
